version: 2
jobs:
  test:
    steps:
      - checkout
      - setup_remote_docker:
        reusable: true
      - run:
        name: Test the demo vars script
        command: bash test/test_get_demo_vars.sh
  build:
    steps:
      - checkout
      - setup_remote_docker:
        reusable: true
      - run:
        name: Build a new docker image
        command: docker build --pull -t bayesimpact/circleci .
      - run:
        name: Push docker image to DockerHub
        command: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
          docker push bayesimpact/circleci

workflows:
  version: 2
  test:
    jobs:
      - test

  weekly:
    triggers:
      - schedule:
          cron: "0 0 * * 5"
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          context: Docker
