version: 2
jobs:
  test:
    docker:
      - image: bayesimpact/circleci
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
      - run:
          name: Test the python scripts
          # TODO(cyrille): Use nose.
          command: ls test/test_*.py | xargs -n1 python3

  build-publish:
    docker:
      - image: bayesimpact/circleci
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
      - run:
          name: Build a new docker image
          command: docker build --pull -t bayesimpact/circleci .
      - run:
          name: Push docker image to DockerHub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
            docker push bayesimpact/circleci
  ping-stale-reviews:
    docker:
      - image: bayesimpact/circleci
    steps:
      - run: ping_reviewers --ping-stale-reviews

workflows:
  version: 2
  test-build-publish:
    jobs:
      - test
      - build-publish:
          filters:
            branches:
              only: main
          context: Docker

  morningly:
    triggers:
      - schedule:
          cron: "30 9 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - ping-stale-reviews:
          context: Slack

  weekly:
    triggers:
      - schedule:
          cron: "0 0 * * 5"
          filters:
            branches:
              only:
                - main
    jobs:
      # To make sure cimg/python:3.9-node is still current.
      - build-publish:
          context: Docker
